# Generated by Django 6.0.5 on 2026-06-01 06:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_jurisdiction_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('aka', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('aka', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('slug', models.SlugField(max_length=255)),
                ('kind', models.CharField(choices=[('district', 'District'), ('school', 'School'), ('company', 'Company (vendor)'), ('nonprofit', 'Nonprofit'), ('committee', 'Committee'), ('campaign', 'Campaign'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='catalog.jurisdiction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'slug'), name='uniq_org_slug_per_jurisdiction'), models.UniqueConstraint(condition=models.Q(('jurisdiction__isnull', True)), fields=('slug',), name='uniq_global_org_slug')],
            },
        ),
    ]
