# Generated by Django 6.0.5 on 2026-06-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_organization_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('committee', 'Committee Meeting'), ('board', 'Board Meeting'), ('board_agenda', 'Board Agenda'), ('called_board', 'Called Board Meeting'), ('other', 'Other')], default='other', max_length=32)),
                ('raw_type_slug', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('source_meeting_id', models.CharField(blank=True, max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('source_path', models.CharField(blank=True, max_length=1024)),
                ('slug', models.SlugField(max_length=255)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='catalog.organization')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='catalog.jurisdiction')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='catalog.source')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('item_type', models.CharField(choices=[('action', 'Action'), ('presentation', 'Presentation'), ('information', 'Information'), ('other', 'Other')], default='other', max_length=32)),
                ('reading_stage', models.CharField(blank=True, choices=[('first', 'First Reading'), ('second', 'Second Reading')], max_length=16)),
                ('outcome_text', models.TextField(blank=True)),
                ('outcome_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('tabled', 'Tabled'), ('postponed', 'Postponed'), ('unanimous', 'Unanimously Approved'), ('none', 'No Outcome')], default='none', max_length=16)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='catalog.meeting')),
            ],
            options={
                'ordering': ['meeting', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('source', 'source_meeting_id'), name='uniq_meeting_per_source_id'),
        ),
    ]
