# Generated by Django 6.0.5 on 2026-06-01 06:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_meeting_agendaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('image', 'Image')], max_length=16)),
                ('r2_key', models.CharField(blank=True, max_length=1024)),
                ('youtube_id', models.CharField(blank=True, max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], default='public', max_length=16)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='catalog.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', max_length=16)),
                ('origin', models.CharField(choices=[('youtube_captions', 'YouTube Captions'), ('whisper', 'faster-whisper')], max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='catalog.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_offset', models.FloatField(default=0)),
                ('end_offset', models.FloatField(blank=True, null=True)),
                ('split_confirmed', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='catalog.mediaasset')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='catalog.meeting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('media', 'meeting'), name='uniq_coverage_media_meeting')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('text', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='catalog.transcript')),
            ],
            options={
                'ordering': ['transcript', 'start'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gin_segment_search')],
            },
        ),
    ]
