# Generated by Django 6.0.5 on 2026-06-01 06:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_media_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('kind', models.CharField(choices=[('minutes', 'Minutes'), ('agenda', 'Agenda'), ('policy', 'Policy'), ('contract', 'Contract'), ('memo', 'Memo'), ('presentation', 'Presentation'), ('report', 'Report'), ('article', 'Article'), ('other', 'Other')], default='other', max_length=32)),
                ('r2_key', models.CharField(blank=True, max_length=1024)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('og_metadata', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True)),
                ('ocr_status', models.CharField(choices=[('has_text', 'Has Text Layer'), ('ocr_needed', 'OCR Needed'), ('empty', 'Empty'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], default='public', max_length=16)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.agendaitem')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.mediaasset')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.meeting')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.source')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gin_document_search')],
            },
        ),
    ]
