# Generated by Django 6.0.5 on 2026-06-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('speaker', 'Speaker'), ('presenter', 'Presenter'), ('staff', 'Staff'), ('invocation', 'Invocation'), ('pledge', 'Pledge of Allegiance')], default='member', max_length=16)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='catalog.meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='catalog.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('value', models.CharField(choices=[('yea', 'Yea'), ('nay', 'Nay'), ('abstain', 'Abstain'), ('absent', 'Absent')], max_length=16)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.agendaitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'agenda_item'), name='uniq_vote_person_item')],
            },
        ),
    ]
