# Generated by Django 6.0.5 on 2026-06-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_vote_appearance'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('quote', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='catalog.document')),
                ('transcript_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='catalog.transcriptsegment')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_citation_fact')],
                'constraints': [models.CheckConstraint(condition=models.Q(('document__isnull', False), ('transcript_segment__isnull', False), _connector='OR'), name='citation_has_evidence')],
            },
        ),
    ]
