# Generated by Django 6.0.5 on 2026-06-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('simple', 'Simple'), ('initial', 'Initial'), ('amended', 'Amended')], default='simple', max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('result_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unanimous', 'Unanimously Approved'), ('none', 'No Recorded Result')], default='none', max_length=16)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='catalog.agendaitem')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions_moved', to='catalog.person')),
                ('seconded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions_seconded', to='catalog.person')),
            ],
            options={
                'ordering': ['agenda_item', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('agenda_item', 'sequence'), name='uniq_motion_item_sequence'), models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_motion')],
            },
        ),
    ]
