# Generated by Django 6.0.5 on 2026-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_motion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendaitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'order'), name='uniq_agendaitem_meeting_order'),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(fields=('person', 'meeting', 'role'), name='uniq_appearance_person_meeting_role'),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_appearance'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('r2_key', ''), _negated=True), fields=('r2_key',), name='uniq_document_r2_key'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(condition=models.Q(('r2_key', ''), _negated=True), fields=('r2_key',), name='uniq_media_r2_key'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('jurisdiction', 'slug'), name='uniq_meeting_slug_per_jurisdiction'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('jurisdiction__isnull', True)), fields=('slug',), name='uniq_global_meeting_slug'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_organization'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_person'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_vote'),
        ),
    ]
