# Generated by Django 6.0.5 on 2026-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_document_search_vector_trigger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(condition=models.Q(('youtube_id', ''), _negated=True), fields=('youtube_id',), name='uniq_media_youtube_id'),
        ),
    ]
