# Generated by Django 6.0.5 on 2026-06-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_transcriptsegment_search_vector_trigger'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('subject_id', models.PositiveBigIntegerField()),
                ('object_id', models.PositiveBigIntegerField()),
                ('predicate', models.CharField(choices=[('board_member_of', 'Board member of'), ('employed_as', 'Employed as'), ('owns', 'Owns'), ('contracts_with', 'Contracts with'), ('donates_to', 'Donates to'), ('affiliated_with', 'Affiliated with')], max_length=32)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('object_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='catalog.source')),
                ('subject_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['subject_ct', 'subject_id'], name='idx_rel_subject'), models.Index(fields=['object_ct', 'object_id'], name='idx_rel_object'), models.Index(fields=['predicate'], name='idx_rel_predicate')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_range_relationship')],
            },
        ),
    ]
