# Generated by Django 6.0.5 on 2026-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='amount_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
